export const TERMS_AND_CONDITIONS = [
	"SEBARANG PERUBAHAN TERTAKLUK KEPADA MASA PEMBAYARAN, PERUBAHAN HARGA SEMASA HOTEL, PENGANGKUTAN DAN VISA",
	"SEBUT HARGA DIATAS TERTAKLUK KEPADA TERMA MASA YANG DITETAPKAN. SEBARANG PERUBAHAN HARGA SELEPAS TAMAT TERMA MASA ADALAH ATAS TANGGUNGAN JEMAAH SENDIRI.",
	"BAYARAN TEMPAHAN AWAL RM 1000/PAX PERLU DIDEBITKAN KE AKAUN AMBANK 88840 0112 8417 , MKM UMRAH HQ",
	"SEBARANG PERTANYAAN DAN MAKLUMBALAS BOLEH HUBUNGI BAHAGIAN UMRAH DI TALIAN 03-7831 6740 / CIK UMU 011 - 021972006",
	"PEMBAYARAN PENUH PERLU DIJELASKAN 60 HARI SEBELUM TARIKH PENERBANGAN",
];
